package model.view.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 04 11:36:36 PDT 2018
// ---------------------------------------------------------------------
public interface DepartmentsView extends ViewObject {
    void dep_method();
}

