package model.view.common;

import oracle.jbo.Row;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 04 12:39:55 PDT 2018
// ---------------------------------------------------------------------
public interface DepartmentsViewRow extends Row {
    void dep_row_method();

    void dep_method_with_parameter(String p1, String p2);
}

