package model.view;


import model.view.common.DepartmentsView;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri May 04 11:00:44 PDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DepartmentsViewImpl extends ViewObjectImpl implements DepartmentsView {
    /**
     * This is the default constructor (do not remove).
     */
    public DepartmentsViewImpl() {
    }
    public void dep_method() {
    // Add event code here...
    System.out.println("I am from dept view impl");
    }
}

